# PROD environment overrides â€” PCI-DSS hardened
replicaCount: 4

image:
  tag: "v1.0.0"
  pullPolicy: Always

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

kafka:
  bootstrapServers: ""  # Set via --set or K8s Secret
  securityProtocol: "SASL_SSL"
  saslMechanism: "PLAIN"
  schemaRegistryUrl: "" # Set via --set or K8s Secret

env:
  APP_ENV: "prod"

networkPolicy:
  enabled: true
  egressPorts:
    - 9092
    - 443
    - 53
