apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: confluent-apps-qa

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: fraud-detection
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

configMapGenerator:
  - name: kafka-config
    behavior: merge
    literals:
      - bootstrap.servers=pkc-qa.us-east-1.aws.confluent.cloud:9092
      - schema.registry.url=https://psrc-qa.us-east-1.aws.confluent.cloud
